<?php return array (
  'AutovmDefaultCurrencyID' => '2',
  'AutovmDefaultCurrencySymbol' => 'Snp$',
  'PlaceCurrencySymbol' => 'option3',
  'ShowExchange' => 'option1',
  'ChargeModuleEnable' => 'option1',
  'ConsoleRoute' => 'https://whmcs.local:8890/console',
  'TopupLink' => '/clientarea.php?action=addfunds',
  'AdminUserSummeryPagePath' => '/admin/clientssummary.php',
  'minimumChargeInAutovmCurrency' => '2',
  'DefaultMonthlyDecimal' => 'option1',
  'DefaultHourlyDecimal' => 'option1',
  'DefaultBalanceDecimalWhmcs' => 'option1',
  'DefaultBalanceDecimalCloud' => 'option1',
  'DefaultChargeAmountDecimalWhmcs' => 'option1',
  'DefaultChargeAmountDecimalCloud' => 'option1',
  'DefaultCreditDecimalWhmcs' => 'option1',
  'DefaultCreditDecimalCloud' => 'option1',
  'DefaultMinimumDecimalWhmcs' => 'option1',
  'DefaultMinimumDecimalCloud' => 'option1',
  'DefaultRatioDecimal' => 'option1',
);